apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-python-basic-rhtap-devfile-multi-component-jiaa
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-qdlf-tenant/mc-two-scenarios/devfile-sample-python-basic-rhtap-devfile-multi-component-jiaa@sha256:6fde528f12ac604d6a4de2800e20a84f580a6017d5f0b4a4a27e7c28566adb11
        name: my-python
        resources: {}
status: {}
